import { QueryProviders } from "@/providers/query-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ThemeProviders } from "@/providers/theme-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
export const dynamic = "force-dynamic";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviders>
          <div className="bg-muted">
            <QueryProviders>
              <Toaster />
              <NuqsAdapter>{children}</NuqsAdapter>
            </QueryProviders>
          </div>
        </ThemeProviders>
      </body>
    </html>
  );
}
